'use client';
import { useEffect, useState } from 'react';

function Login({onDone}){
  const [pin,setPin]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);
  async function submit(e){e.preventDefault();setBusy(true);setError('');const r=await fetch('/api/auth/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({pin})});const j=await r.json().catch(()=>({}));setBusy(false);if(!r.ok)return setError(j.error||'Login failed.');if(j.role!=='manager'){await fetch('/api/auth/logout',{method:'POST'});return setError('Manager PIN required.');}onDone();}
  return <main className="page"><div className="card login"><div className="logo-big">HANOK</div><p className="muted">Manager · Access & PIN Settings</p>{error&&<div className="error">{error}</div>}<form onSubmit={submit} style={{marginTop:16}}><div className="field"><label>Manager PIN</label><input type="password" inputMode="numeric" value={pin} onChange={e=>setPin(e.target.value)} autoFocus/></div><button className="btn brand" style={{width:'100%',marginTop:12}} disabled={busy}>{busy?'Signing in…':'SIGN IN'}</button></form></div></main>;
}

function PinCard({role,title,description,onChanged}){
  const [pin,setPin]=useState('');const [confirmPin,setConfirmPin]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [message,setMessage]=useState('');
  async function save(){setError('');setMessage('');if(!/^\d{4,8}$/.test(pin))return setError('PIN must be 4 to 8 digits.');if(pin!==confirmPin)return setError('PIN confirmation does not match.');setBusy(true);const r=await fetch('/api/manager/security',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({role,new_pin:pin})});const j=await r.json().catch(()=>({}));setBusy(false);if(!r.ok)return setError(j.error||'Unable to change PIN.');setPin('');setConfirmPin('');setMessage(`${title} PIN updated. Existing ${title.toLowerCase()} logins have been signed out.`);onChanged?.();}
  return <div className="card"><div className="muted">{role.toUpperCase()} ACCESS</div><h2 style={{margin:'4px 0 8px'}}>{title} PIN</h2><p className="muted">{description}</p>{error&&<div className="error" style={{marginBottom:12}}>{error}</div>}{message&&<div className="notice" style={{marginBottom:12}}>{message}</div>}<div className="grid grid-2"><div className="field"><label>New PIN</label><input type="password" inputMode="numeric" autoComplete="new-password" placeholder="4–8 digits" value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,'').slice(0,8))}/></div><div className="field"><label>Confirm New PIN</label><input type="password" inputMode="numeric" autoComplete="new-password" placeholder="Repeat PIN" value={confirmPin} onChange={e=>setConfirmPin(e.target.value.replace(/\D/g,'').slice(0,8))}/></div></div><button className="btn brand" style={{marginTop:14}} disabled={busy||!pin||!confirmPin} onClick={()=>confirm(`Change the ${title} PIN? All currently logged-in ${title.toLowerCase()} devices will be signed out.`)&&save()}>{busy?'UPDATING…':`CHANGE ${role.toUpperCase()} PIN`}</button></div>;
}

export default function ManagerSecurityPage(){
  const [auth,setAuth]=useState(null);const [globalMessage,setGlobalMessage]=useState('');
  async function verify(){const r=await fetch('/api/manager/security',{cache:'no-store'});setAuth(r.ok);}
  useEffect(()=>{verify();},[]);
  async function logout(){await fetch('/api/auth/logout',{method:'POST'});setAuth(false);}
  if(auth===null)return <main className="page"><div className="card">Checking Manager access…</div></main>;
  if(!auth)return <Login onDone={()=>setAuth(true)}/>;
  return <><div className="topbar"><div className="logo">HANOK<small>WAGGA WAGGA · ACCESS & PIN SETTINGS</small></div><div className="spacer"/><a href="/manager/menu" className="btn secondary small">Manager Control</a><a href="/staff" className="btn secondary small">Staff Dashboard</a><button className="btn secondary small" onClick={logout}>Logout</button></div><main className="page" style={{maxWidth:900}}><section className="hero"><h1>Access & PIN Settings</h1><p>Manager-only control for Staff and Kitchen login PINs.</p></section>{globalMessage&&<div className="notice" style={{marginTop:14}}>{globalMessage}</div>}<div className="notice" style={{marginTop:16}}><b>Security behavior:</b> PINs are stored as hashes, never displayed back to the Manager. Changing a PIN immediately signs out all currently logged-in devices for that role. The new PIN cannot match the Manager PIN or the other operational role PIN.</div><div className="grid grid-2" style={{marginTop:16}}><PinCard role="staff" title="Staff" description="Used by floor staff to open and manage table sessions." onChanged={()=>setGlobalMessage('Staff access updated successfully.')}/><PinCard role="kitchen" title="Kitchen" description="Used by Meat KDS and Hot Kitchen KDS screens." onChanged={()=>setGlobalMessage('Kitchen access updated successfully.')}/></div><div className="card" style={{marginTop:16}}><h3 style={{marginTop:0}}>Manager PIN</h3><p className="muted" style={{marginBottom:0}}>Manager PIN changes are intentionally not available on this page to reduce the risk of accidentally locking management out of the system.</p></div></main></>;
}
