'use client';

import { useEffect, useMemo, useState } from 'react';
import QRCode from 'qrcode';

const PRODUCTION_ORIGIN = 'https://orderhanokbbqwagga.com';

function Login({ onDone }) {
  const [pin,setPin]=useState('');
  const [error,setError]=useState('');
  const [busy,setBusy]=useState(false);
  async function submit(e){e.preventDefault();setBusy(true);setError('');const r=await fetch('/api/auth/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({pin})});const j=await r.json().catch(()=>({}));setBusy(false);if(!r.ok)return setError(j.error||'Login failed.');if(j.role!=='manager'){await fetch('/api/auth/logout',{method:'POST'});return setError('Manager PIN required.');}onDone();}
  return <main className="page"><div className="card login"><div className="logo-big">HANOK</div><p className="muted">Manager · Table QR Codes</p>{error&&<div className="error">{error}</div>}<form onSubmit={submit} style={{marginTop:16}}><div className="field"><label>Manager PIN</label><input type="password" inputMode="numeric" value={pin} onChange={e=>setPin(e.target.value)} autoFocus/></div><button className="btn brand" style={{width:'100%',marginTop:12}} disabled={busy}>{busy?'Signing in…':'SIGN IN'}</button></form></div></main>;
}

function QRCard({table}){
  const url=useMemo(()=>`${PRODUCTION_ORIGIN}/t/${table.token}`,[table.token]);
  const [src,setSrc]=useState(''); const [error,setError]=useState('');
  useEffect(()=>{let live=true;QRCode.toDataURL(url,{errorCorrectionLevel:'H',margin:1,width:720,color:{dark:'#000000',light:'#ffffff'}}).then(x=>{if(live){setSrc(x);setError('')}}).catch(e=>{if(live)setError(e.message||'QR generation failed')});return()=>{live=false};},[url]);
  return <div className="label-wrap"><div className="qr-label"><div className="hanok-word">Hanok<span className="seal">한옥</span></div><div className="fine-bbq"><i/>KOREAN FINE BBQ<i/></div><div className="qr-box">{src?<img src={src} alt={`${table.name} QR code`}/>:<span>{error||'Generating…'}</span>}</div><div className="scan">▯&nbsp; SCAN TO ORDER</div><div className="label-line"/><div className="table-row"><span>TABLE</span><strong>{table.name}</strong><i/></div></div></div>;
}

export default function ManagerQRPage(){
  const [auth,setAuth]=useState(true); const [tables,setTables]=useState([]); const [error,setError]=useState('');
  async function load(){const r=await fetch('/api/staff/tables',{cache:'no-store'});const j=await r.json().catch(()=>({}));if(r.status===401){setAuth(false);setTables([]);return;}if(!r.ok){setError(j.error||'Unable to load tables.');return;}if(j.role!=='manager'){await fetch('/api/auth/logout',{method:'POST'});setAuth(false);setTables([]);setError('Manager PIN required.');return;}setAuth(true);setTables(j.tables||[]);setError('');}
  useEffect(()=>{load();},[]);
  async function logout(){await fetch('/api/auth/logout',{method:'POST'});setAuth(false);setTables([]);}
  if(!auth)return <Login onDone={()=>{setAuth(true);load();}}/>;
  return <><style>{`
    .label-sheet{display:grid;grid-template-columns:repeat(auto-fill,minmax(210px,1fr));gap:22px;margin-top:18px}.label-wrap{display:flex;justify-content:center}.qr-label{width:200px;height:200px;box-sizing:border-box;border-radius:50%;background:#050505;color:#fff;border:3px solid #050505;box-shadow:inset 0 0 0 2px #e31b23,inset 0 0 0 7px #050505;padding:18px 21px 14px;text-align:center;display:flex;flex-direction:column;align-items:center;overflow:hidden}.hanok-word{font-size:31px;line-height:32px;font-weight:900;font-style:italic;letter-spacing:-2px;white-space:nowrap}.seal{display:inline-flex;align-items:center;justify-content:center;background:#e31b23;color:#fff;font-style:normal;font-size:7px;letter-spacing:0;width:16px;height:27px;border-radius:8px;margin-left:4px;vertical-align:4px}.fine-bbq{width:100%;display:flex;align-items:center;gap:6px;justify-content:center;font-size:7.5px;font-weight:800;letter-spacing:1.5px;margin:1px 0 6px;white-space:nowrap}.fine-bbq i,.table-row i{display:block;height:1.5px;background:#e31b23;flex:1}.qr-box{width:94px;height:94px;background:#fff;border-radius:8px;padding:5px;box-sizing:border-box;display:grid;place-items:center}.qr-box img{width:100%;height:100%;display:block}.qr-box span{color:#555;font-size:7px}.scan{font-size:8px;font-weight:800;letter-spacing:1px;margin-top:5px;white-space:nowrap}.label-line{width:100%;height:1.5px;background:#e31b23;margin-top:4px}.table-row{width:100%;height:35px;display:flex;align-items:center;justify-content:center;gap:7px}.table-row span{font-size:8px;font-weight:900;letter-spacing:.8px}.table-row strong{color:#e31b23;font-size:30px;line-height:30px;font-weight:950;letter-spacing:-1px}.table-row i{max-width:18px}.print-note{margin-top:12px;font-size:13px}
    @media print{@page{margin:5mm}.no-print,.topbar{display:none!important}.page{max-width:none!important;padding:0!important;margin:0!important}.label-sheet{display:grid!important;grid-template-columns:repeat(3,50mm)!important;grid-auto-rows:50mm!important;gap:3mm!important;justify-content:center!important;margin:0!important}.label-wrap{width:50mm!important;height:50mm!important;break-inside:avoid!important;page-break-inside:avoid!important}.qr-label{width:50mm!important;height:50mm!important;box-shadow:inset 0 0 0 .45mm #e31b23,inset 0 0 0 1.6mm #050505!important;padding:4.5mm 5.2mm 3mm!important}.hanok-word{font-size:7.8mm!important;line-height:8mm!important}.seal{font-size:1.7mm!important;width:4mm!important;height:6.6mm!important}.fine-bbq{font-size:1.8mm!important;letter-spacing:.35mm!important;margin:.3mm 0 1.3mm!important;gap:1.3mm!important}.qr-box{width:23.5mm!important;height:23.5mm!important;border-radius:2mm!important;padding:1.2mm!important}.scan{font-size:2mm!important;letter-spacing:.25mm!important;margin-top:1.2mm!important}.label-line{height:.35mm!important;margin-top:1mm!important}.table-row{height:8mm!important;gap:1.8mm!important}.table-row span{font-size:2mm!important}.table-row strong{font-size:7.5mm!important;line-height:7.5mm!important}.table-row i{max-width:4.5mm!important}body{background:#fff!important}}
  `}</style><div className="topbar no-print"><div className="logo">HANOK<small>WAGGA WAGGA · TABLE QR CODES</small></div><div className="spacer"/><a href="/manager/tables" className="btn secondary small">Table Management</a><a href="/manager/menu" className="btn secondary small">Manager Menu</a><a href="/staff" className="btn secondary small">Staff Dashboard</a><button className="btn secondary small" onClick={logout}>Logout</button></div><main className="page" style={{maxWidth:1120}}><section className="hero no-print"><h1>50mm Round Table QR Codes</h1><p>All active tables are formatted as 50mm circular Hanok labels, ready for label-sheet or sticker printing.</p><div className="notice" style={{marginTop:12}}><b>Official QR domain:</b> {PRODUCTION_ORIGIN}<br/><b>Print size:</b> 50mm × 50mm · Scale 100% / Actual Size · Disable “Fit to page”.</div><div className="actions" style={{marginTop:14}}><button className="btn brand" disabled={!tables.length} onClick={()=>window.print()}>PRINT ALL {tables.length} ACTIVE TABLES</button></div></section>{error&&<div className="error" style={{marginTop:12}}>{error}</div>}{!tables.length&&!error?<div className="card" style={{marginTop:16}}>No active tables found.</div>:<div className="label-sheet">{tables.map(t=><QRCard key={t.id} table={t}/>)}</div>}</main></>;
}
