package com.hanok.printbridge;

import android.app.*;import android.content.*;import android.content.pm.ServiceInfo;import android.os.*;import org.json.*;import java.io.*;import java.net.*;import java.nio.charset.StandardCharsets;import java.text.SimpleDateFormat;import java.util.*;import java.util.concurrent.*;

public class BridgeService extends Service {
 private static final String CHANNEL="hanok_bridge"; private final ScheduledExecutorService exec=Executors.newSingleThreadScheduledExecutor(); private volatile boolean busy=false; private String startedAt; private SharedPreferences prefs;
 @Override public void onCreate(){super.onCreate();prefs=getSharedPreferences("bridge",MODE_PRIVATE);startedAt=isoNow();createChannel();Notification n=notification("Running · waiting for new orders");if(Build.VERSION.SDK_INT>=34)startForeground(1001,n,ServiceInfo.FOREGROUND_SERVICE_TYPE_SPECIAL_USE);else startForeground(1001,n);}
 @Override public int onStartCommand(Intent i,int f,int id){exec.scheduleWithFixedDelay(()->{if(busy)return;busy=true;try{poll();}catch(Exception e){update("Cloud error · "+shortMsg(e));}finally{busy=false;}},0,2,TimeUnit.SECONDS);return START_STICKY;} @Override public void onDestroy(){exec.shutdownNow();super.onDestroy();} @Override public IBinder onBind(Intent i){return null;}
 private void poll() throws Exception{String base=trimSlash(prefs.getString("url","https://orderhanokbbqwagga.com"));String secret=prefs.getString("secret","");if(secret.isEmpty())throw new Exception("Missing secret");int st=prefs.getInt("station",0);String station=st==1?"meat":st==2?"hot":"";String q="?since="+URLEncoder.encode(startedAt,"UTF-8")+(station.isEmpty()?"":"&station="+station);HttpURLConnection c=(HttpURLConnection)new URL(base+"/api/print/pending"+q).openConnection();c.setConnectTimeout(5000);c.setReadTimeout(8000);c.setRequestProperty("x-print-secret",secret);c.setRequestProperty("accept","application/json");int code=c.getResponseCode();String body=read(code>=400?c.getErrorStream():c.getInputStream());if(code<200||code>=300)throw new Exception("API "+code);JSONArray orders=new JSONObject(body).optJSONArray("orders");if(orders==null)return;for(int x=0;x<orders.length();x++){JSONObject o=orders.getJSONObject(x);String id=o.optString("id");try{update("Printing "+o.optString("table_name"));print(o);mark(base,secret,id,true);update("Printed "+o.optString("table_name"));}catch(Exception e){try{mark(base,secret,id,false);}catch(Exception ignored){}update("Print failed · "+shortMsg(e));}}}
 private void print(JSONObject o)throws Exception{String host=prefs.getString("host","192.168.0.192");int port=Integer.parseInt(prefs.getString("port","9100"));Socket s=new Socket();s.connect(new InetSocketAddress(host,port),5000);s.setSoTimeout(5000);OutputStream out=s.getOutputStream();out.write(ticket(o));out.write(new byte[]{0x1d,0x56,0x00});out.flush();s.close();}
 private byte[] ticket(JSONObject o)throws Exception{ByteArrayOutputStream b=new ByteArrayOutputStream();JSONArray items=o.optJSONArray("order_items");if(items==null)items=new JSONArray();int count=0;for(int i=0;i<items.length();i++)count+=items.getJSONObject(i).optInt("qty",0);String table=o.optString("table_name","TABLE"),source=o.optString("source",""),label=o.optString("label","").toUpperCase(Locale.ROOT),station=o.optString("station","");String section=source.equals("starter")?(label.contains("NO PORK")?"NO PORK STARTER":"STARTER PLATTER"):(station.equals("hot")?"HOT KITCHEN":"BBQ MEAT");String orderType=source.equals("starter")?"STARTER":(o.optInt("round_no",0)>0?"ROUND "+o.optInt("round_no"):"NEW ORDER");String created=o.optString("created_at","");String time=created.length()>15?created.substring(11,16):"";String order=o.optString("id","");if(order.length()>8)order=order.substring(0,8).toUpperCase(Locale.ROOT);write(b,new byte[]{0x1b,0x40,0x1b,0x61,0x01,0x1b,0x45,0x01,0x1d,0x21,0x11});txt(b,"HANOK WAGGA\n");write(b,new byte[]{0x1d,0x21,0x33});txt(b,table+"\n");write(b,new byte[]{0x1d,0x21,0x11,0x1d,0x42,0x01});txt(b," "+section+" \n");write(b,new byte[]{0x1d,0x42,0x00,0x1d,0x21,0x10});txt(b,"\n"+orderType+"\n");write(b,new byte[]{0x1d,0x21,0x00,0x1b,0x61,0x00});txt(b,"------------------------------------------\n");for(int i=0;i<items.length();i++){JSONObject it=items.getJSONObject(i);write(b,new byte[]{0x1b,0x45,0x01,0x1d,0x21,0x10});txt(b,it.optString("item_name","Item")+"\n");write(b,new byte[]{0x1d,0x21,0x11});txt(b,"  x "+it.optInt("qty",0)+"\n");write(b,new byte[]{0x1d,0x21,0x00,0x1b,0x45,0x00});txt(b,"..........................................\n");}write(b,new byte[]{0x1b,0x61,0x01,0x1b,0x45,0x01,0x1d,0x21,0x11});txt(b,"ITEMS: "+count+"\n");write(b,new byte[]{0x1d,0x21,0x00,0x1b,0x61,0x00});txt(b,"ORDER: "+order+"\nTIME:  "+time+"\n\n\n");return b.toByteArray();}
 private void mark(String base,String secret,String id,boolean printed)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(base+"/api/print/pending").openConnection();c.setConnectTimeout(5000);c.setReadTimeout(8000);c.setRequestMethod("PATCH");c.setDoOutput(true);c.setRequestProperty("content-type","application/json");c.setRequestProperty("x-print-secret",secret);byte[] body=("{\"order_id\":\""+id+"\",\"printed\":"+printed+",\"attempts\":1}").getBytes(StandardCharsets.UTF_8);c.getOutputStream().write(body);if(c.getResponseCode()<200||c.getResponseCode()>=300)throw new Exception("Mark failed");c.disconnect();}
 private void createChannel(){if(Build.VERSION.SDK_INT>=26){NotificationChannel c=new NotificationChannel(CHANNEL,"Hanok Print Bridge",NotificationManager.IMPORTANCE_LOW);c.setDescription("Keeps the restaurant print bridge active");getSystemService(NotificationManager.class).createNotificationChannel(c);}}
 private Notification notification(String msg){Intent i=new Intent(this,MainActivity.class);PendingIntent p=PendingIntent.getActivity(this,0,i,PendingIntent.FLAG_IMMUTABLE|PendingIntent.FLAG_UPDATE_CURRENT);return new Notification.Builder(this,CHANNEL).setSmallIcon(android.R.drawable.stat_sys_upload_done).setContentTitle("Hanok Print Bridge").setContentText(msg).setContentIntent(p).setOngoing(true).build();}
 private void update(String msg){((NotificationManager)getSystemService(NOTIFICATION_SERVICE)).notify(1001,notification(msg));}
 private static String read(InputStream in)throws Exception{if(in==null)return"";ByteArrayOutputStream b=new ByteArrayOutputStream();byte[]x=new byte[4096];int n;while((n=in.read(x))>0)b.write(x,0,n);return b.toString("UTF-8");} private static void write(ByteArrayOutputStream b,byte[]x)throws Exception{b.write(x);} private static void txt(ByteArrayOutputStream b,String s)throws Exception{b.write(s.getBytes(StandardCharsets.US_ASCII));} private static String isoNow(){return new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSXXX",Locale.US).format(new Date());} private static String trimSlash(String s){while(s.endsWith("/"))s=s.substring(0,s.length()-1);return s;} private static String shortMsg(Exception e){String s=e.getMessage();return s==null?e.getClass().getSimpleName():(s.length()>45?s.substring(0,45):s);}
}
