package com.hanok.printbridge;

import android.app.*;import android.content.*;import android.content.pm.ServiceInfo;import android.os.*;import org.json.*;import java.io.*;import java.net.*;import java.nio.charset.StandardCharsets;import java.text.SimpleDateFormat;import java.util.*;import java.util.concurrent.*;

public class BridgeService extends Service {
 public static final String ACTION_STOP="com.hanok.printbridge.STOP"; private static final String CHANNEL="hanok_bridge";
 private final ScheduledExecutorService exec=Executors.newSingleThreadScheduledExecutor(); private volatile boolean busy=false,scheduled=false; private String bridgeEpoch; private SharedPreferences prefs; private final Map<String,Long> firstSeen=new HashMap<>();
 @Override public void onCreate(){super.onCreate();prefs=getSharedPreferences(BridgeConfig.PREFS,MODE_PRIVATE);bridgeEpoch=prefs.getString("bridge_epoch","");if(bridgeEpoch.isEmpty()){bridgeEpoch=isoNow();prefs.edit().putString("bridge_epoch",bridgeEpoch).apply();}createChannel();Notification n=notification("Running · total + split printers");if(Build.VERSION.SDK_INT>=34)startForeground(1001,n,ServiceInfo.FOREGROUND_SERVICE_TYPE_SPECIAL_USE);else startForeground(1001,n);prefs.edit().putBoolean("enabled",true).putString("status","Running · waiting for orders").apply();}
 @Override public int onStartCommand(Intent i,int f,int id){if(i!=null&&ACTION_STOP.equals(i.getAction())){prefs.edit().putBoolean("enabled",false).putString("status","Stopped").apply();stopForeground(true);stopSelf();return START_NOT_STICKY;}if(!scheduled){scheduled=true;exec.scheduleWithFixedDelay(()->{if(busy)return;busy=true;try{poll();}catch(Exception e){setStatus("Cloud error · "+shortMsg(e));}finally{busy=false;}},0,2,TimeUnit.SECONDS);}return START_STICKY;}
 @Override public void onDestroy(){prefs.edit().putBoolean("enabled",false).putString("status","Stopped").apply();exec.shutdownNow();super.onDestroy();}@Override public IBinder onBind(Intent i){return null;}
 private void poll() throws Exception{String base=BridgeConfig.BASE_URL,secret=BridgeConfig.PRINT_SECRET;String q="?since="+URLEncoder.encode(bridgeEpoch,"UTF-8");HttpURLConnection c=(HttpURLConnection)new URL(base+"/api/print/pending"+q).openConnection();c.setConnectTimeout(5000);c.setReadTimeout(8000);c.setRequestProperty("x-print-secret",secret);c.setRequestProperty("accept","application/json");int code=c.getResponseCode();String body=read(code>=400?c.getErrorStream():c.getInputStream());if(code<200||code>=300)throw new Exception("API "+code);JSONArray orders=new JSONObject(body).optJSONArray("orders");if(orders==null||orders.length()==0){setStatus("Running · waiting for orders");return;}Map<String,List<JSONObject>> groups=new LinkedHashMap<>();for(int x=0;x<orders.length();x++){JSONObject o=orders.getJSONObject(x);String key=groupKey(o);groups.computeIfAbsent(key,k->new ArrayList<>()).add(o);firstSeen.putIfAbsent(key,System.currentTimeMillis());}for(Map.Entry<String,List<JSONObject>> entry:groups.entrySet()){String key=entry.getKey();List<JSONObject> group=entry.getValue();long age=System.currentTimeMillis()-firstSeen.getOrDefault(key,System.currentTimeMillis());if(age<1800)continue;String table=group.get(0).optString("table_name","TABLE");setStatus("Printing "+table);try{if(!wasDelivered("total",key)){printTotal(group);rememberDelivered("total",key);}for(JSONObject o:group){JSONArray items=o.optJSONArray("order_items");if(items==null||items.length()==0)continue;String orderId=o.optString("id","");if(!wasDelivered("split",orderId)){printOneSplit(o);rememberDelivered("split",orderId);}}for(JSONObject o:group)mark(base,secret,o.optString("id"),true);firstSeen.remove(key);setStatus("Printed "+table+" · total + split");}catch(Exception e){setStatus("Print failed · "+shortMsg(e));}}}
 private String receiptKey(String type,String id){return "delivered_"+type+"_"+Integer.toHexString(id.hashCode());}private boolean wasDelivered(String type,String id){return prefs.getBoolean(receiptKey(type,id),false);}private void rememberDelivered(String type,String id){prefs.edit().putBoolean(receiptKey(type,id),true).apply();}
 private String groupKey(JSONObject o){return o.optString("table_name","")+"|"+o.optString("source","")+"|"+o.optInt("round_no",0)+"|"+o.optString("label","");}
 private void printTotal(List<JSONObject> group)throws Exception{send(prefs.getString("total_host",BridgeConfig.DEFAULT_TOTAL_IP),prefs.getInt("port",BridgeConfig.DEFAULT_PORT),totalTicket(group));}private void printOneSplit(JSONObject o)throws Exception{send(prefs.getString("split_host",BridgeConfig.DEFAULT_SPLIT_IP),prefs.getInt("port",BridgeConfig.DEFAULT_PORT),stationTicket(o));}
 private void send(String host,int port,byte[] body)throws Exception{if(host==null||host.isEmpty())throw new Exception("Printer IP missing");Socket s=new Socket();s.connect(new InetSocketAddress(host,port),5000);s.setSoTimeout(5000);OutputStream out=s.getOutputStream();out.write(body);out.write(new byte[]{0x1d,0x56,0x00});out.flush();s.close();}
 private byte[] totalTicket(List<JSONObject> group)throws Exception{JSONObject first=group.get(0);String table=first.optString("table_name","TABLE"),source=first.optString("source",""),label=first.optString("label","").toUpperCase(Locale.ROOT);String type=source.equals("starter")?(label.contains("NO PORK")?"NO PORK STARTER":"STARTER"):(first.optInt("round_no",0)>0?"ROUND "+first.optInt("round_no"):"NEW ORDER");List<JSONObject> meat=new ArrayList<>(),hot=new ArrayList<>();int count=0;String created=first.optString("created_at","");for(JSONObject o:group){JSONArray a=o.optJSONArray("order_items");if(a==null)continue;for(int i=0;i<a.length();i++){JSONObject it=a.getJSONObject(i);count+=it.optInt("qty",0);if(o.optString("station","").equals("hot"))hot.add(it);else meat.add(it);}}ByteArrayOutputStream b=new ByteArrayOutputStream();header(b,table,"TOTAL ORDER",type);if(!meat.isEmpty()){section(b,"BBQ MEAT");items(b,meat);}if(!hot.isEmpty()){section(b,"HOT KITCHEN");items(b,hot);}footer(b,count,created);return b.toByteArray();}
 private byte[] stationTicket(JSONObject o)throws Exception{JSONArray a=o.optJSONArray("order_items");if(a==null)a=new JSONArray();List<JSONObject> its=new ArrayList<>();int count=0;for(int i=0;i<a.length();i++){JSONObject it=a.getJSONObject(i);its.add(it);count+=it.optInt("qty",0);}String source=o.optString("source",""),label=o.optString("label","").toUpperCase(Locale.ROOT),station=o.optString("station","");String sec=source.equals("starter")?(label.contains("NO PORK")?"NO PORK STARTER":"STARTER PLATTER"):(station.equals("hot")?"HOT KITCHEN":"BBQ MEAT");String type=source.equals("starter")?"STARTER":(o.optInt("round_no",0)>0?"ROUND "+o.optInt("round_no"):"NEW ORDER");ByteArrayOutputStream b=new ByteArrayOutputStream();header(b,o.optString("table_name","TABLE"),sec,type);items(b,its);footer(b,count,o.optString("created_at",""));return b.toByteArray();}
 // Compact 80mm layout: table 2x2, section 2x1, normal-height bold item rows.
 private void header(ByteArrayOutputStream b,String table,String sec,String type)throws Exception{write(b,new byte[]{0x1b,0x40,0x1b,0x61,0x01,0x1b,0x45,0x01});txt(b,"HANOK WAGGA\n");write(b,new byte[]{0x1d,0x21,0x11});txt(b,table+"\n");write(b,new byte[]{0x1d,0x21,0x10});txt(b,sec+"\n");write(b,new byte[]{0x1d,0x21,0x00});txt(b,type+"\n");write(b,new byte[]{0x1b,0x61,0x00,0x1b,0x45,0x00});txt(b,"------------------------------------------\n");}
 private void section(ByteArrayOutputStream b,String name)throws Exception{write(b,new byte[]{0x1b,0x45,0x01,0x1d,0x21,0x10});txt(b,name+"\n");write(b,new byte[]{0x1d,0x21,0x00,0x1b,0x45,0x00});}
 private void items(ByteArrayOutputStream b,List<JSONObject> list)throws Exception{for(JSONObject it:list){String name=it.optString("item_name","Item");int qty=it.optInt("qty",0);write(b,new byte[]{0x1b,0x45,0x01,0x1d,0x21,0x00});txt(b,itemLine(name,qty));write(b,new byte[]{0x1b,0x45,0x00});}}
 private String itemLine(String name,int qty){String q="x"+qty;int width=42;if(name.length()+q.length()+1<=width){StringBuilder s=new StringBuilder(name);while(s.length()<width-q.length())s.append(' ');return s+q+"\n";}return name+"\n"+spaces(Math.max(1,width-q.length()))+q+"\n";}
 private String spaces(int n){StringBuilder s=new StringBuilder();for(int i=0;i<n;i++)s.append(' ');return s.toString();}
 private void footer(ByteArrayOutputStream b,int count,String created)throws Exception{String time=created.length()>15?created.substring(11,16):"";write(b,new byte[]{0x1b,0x45,0x00});txt(b,"------------------------------------------\n");write(b,new byte[]{0x1b,0x45,0x01});String left="ITEMS: "+count,right=time;StringBuilder row=new StringBuilder(left);while(row.length()<42-right.length())row.append(' ');row.append(right).append('\n');txt(b,row.toString());write(b,new byte[]{0x1b,0x45,0x00});txt(b,"==========================================\n\n");}
 private void mark(String base,String secret,String id,boolean printed)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(base+"/api/print/pending").openConnection();c.setConnectTimeout(5000);c.setReadTimeout(8000);c.setRequestMethod("PATCH");c.setDoOutput(true);c.setRequestProperty("content-type","application/json");c.setRequestProperty("x-print-secret",secret);byte[] body=("{\"order_id\":\""+id+"\",\"printed\":"+printed+",\"attempts\":1}").getBytes(StandardCharsets.UTF_8);c.getOutputStream().write(body);if(c.getResponseCode()<200||c.getResponseCode()>=300)throw new Exception("Mark failed");c.disconnect();}
 private void createChannel(){if(Build.VERSION.SDK_INT>=26){NotificationChannel c=new NotificationChannel(CHANNEL,"Hanok Wagga Print Bridge",NotificationManager.IMPORTANCE_LOW);c.setDescription("Keeps Wagga kitchen printing active");getSystemService(NotificationManager.class).createNotificationChannel(c);}}private Notification notification(String msg){Intent i=new Intent(this,MainActivity.class);PendingIntent p=PendingIntent.getActivity(this,0,i,PendingIntent.FLAG_IMMUTABLE|PendingIntent.FLAG_UPDATE_CURRENT);return new Notification.Builder(this,CHANNEL).setSmallIcon(android.R.drawable.stat_sys_upload_done).setContentTitle("Hanok Wagga Print Bridge").setContentText(msg).setContentIntent(p).setOngoing(true).build();}private void setStatus(String msg){prefs.edit().putBoolean("enabled",true).putString("status",msg).apply();((NotificationManager)getSystemService(NOTIFICATION_SERVICE)).notify(1001,notification(msg));}
 private static String read(InputStream in)throws Exception{if(in==null)return"";ByteArrayOutputStream b=new ByteArrayOutputStream();byte[]x=new byte[4096];int n;while((n=in.read(x))>0)b.write(x,0,n);return b.toString("UTF-8");}private static void write(ByteArrayOutputStream b,byte[]x)throws Exception{b.write(x);}private static void txt(ByteArrayOutputStream b,String s)throws Exception{b.write(s.getBytes(StandardCharsets.US_ASCII));}private static String isoNow(){return new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSXXX",Locale.US).format(new Date());}private static String shortMsg(Exception e){String s=e.getMessage();return s==null?e.getClass().getSimpleName():(s.length()>45?s.substring(0,45):s);}
}
