package com.hanok.printbridge;

import android.Manifest;import android.app.Activity;import android.content.*;import android.content.pm.PackageManager;import android.graphics.Color;import android.os.*;import android.widget.*;import java.io.OutputStream;import java.net.*;import java.nio.charset.StandardCharsets;

public class MainActivity extends Activity {
 private EditText url,secret,host,port; private Spinner station; private TextView status; private SharedPreferences prefs;
 @Override public void onCreate(Bundle b){super.onCreate(b);prefs=getSharedPreferences("bridge",MODE_PRIVATE);if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},100);buildUi();}
 private TextView label(String t){TextView v=new TextView(this);v.setText(t);v.setTextSize(13);v.setTextColor(Color.DKGRAY);v.setPadding(0,14,0,4);return v;} private EditText field(String v){EditText e=new EditText(this);e.setText(v);e.setTextSize(16);e.setSingleLine(true);e.setPadding(14,10,14,10);return e;} private Button button(String t){Button b=new Button(this);b.setText(t);b.setTextSize(16);b.setAllCaps(false);return b;}
 private void buildUi(){ScrollView scroll=new ScrollView(this);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(28,28,28,36);root.setBackgroundColor(Color.rgb(248,245,239));TextView title=new TextView(this);title.setText("HANOK PRINT BRIDGE");title.setTextSize(28);title.setTextColor(Color.rgb(55,25,20));title.setTypeface(null,1);root.addView(title);TextView sub=new TextView(this);sub.setText("Android test bridge · Cloud → LAN printer");sub.setTextSize(14);sub.setPadding(0,4,0,18);root.addView(sub);root.addView(label("Cloud URL"));url=field(prefs.getString("url","https://orderhanokbbqwagga.com"));root.addView(url);root.addView(label("Print Agent Secret"));secret=field(prefs.getString("secret",""));secret.setInputType(0x81);root.addView(secret);root.addView(label("Printer IP"));host=field(prefs.getString("host","192.168.0.192"));root.addView(host);root.addView(label("Printer Port"));port=field(prefs.getString("port","9100"));port.setInputType(2);root.addView(port);root.addView(label("Station"));station=new Spinner(this);String[] s={"All (test mode)","Meat only","Hot Kitchen only"};station.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,s));station.setSelection(prefs.getInt("station",0));root.addView(station);status=new TextView(this);status.setText("● Bridge stopped");status.setTextSize(16);status.setTypeface(null,1);status.setTextColor(Color.rgb(150,45,35));status.setPadding(0,24,0,12);root.addView(status);Button test=button("TEST PRINT");root.addView(test);test.setOnClickListener(v->testPrint());Button start=button("START BRIDGE");root.addView(start);start.setOnClickListener(v->startBridge());Button stop=button("STOP BRIDGE");root.addView(stop);stop.setOnClickListener(v->{stopService(new Intent(this,BridgeService.class));status.setText("● Bridge stopped");status.setTextColor(Color.rgb(150,45,35));});TextView note=new TextView(this);note.setText("Keep this phone connected to the restaurant Wi‑Fi and plugged into power. The foreground notification should remain visible while the bridge is running.");note.setTextSize(13);note.setPadding(0,20,0,0);root.addView(note);scroll.addView(root);setContentView(scroll);}
 private void save(){prefs.edit().putString("url",url.getText().toString().trim()).putString("secret",secret.getText().toString().trim()).putString("host",host.getText().toString().trim()).putString("port",port.getText().toString().trim()).putInt("station",station.getSelectedItemPosition()).apply();}
 private void startBridge(){save();if(secret.getText().toString().trim().isEmpty()){Toast.makeText(this,"Enter Print Agent Secret",Toast.LENGTH_LONG).show();return;}Intent i=new Intent(this,BridgeService.class);if(Build.VERSION.SDK_INT>=26)startForegroundService(i);else startService(i);status.setText("● Bridge running");status.setTextColor(Color.rgb(30,120,70));Toast.makeText(this,"Bridge started",Toast.LENGTH_SHORT).show();}
 private void testPrint(){save();status.setText("● Testing printer…");status.setTextColor(Color.rgb(160,100,15));new Thread(()->{try{String h=prefs.getString("host","192.168.0.192");int p=Integer.parseInt(prefs.getString("port","9100"));Socket s=new Socket();s.connect(new InetSocketAddress(h,p),4000);OutputStream out=s.getOutputStream();out.write(new byte[]{0x1b,0x40,0x1b,0x61,0x01,0x1b,0x45,0x01,0x1d,0x21,0x11});out.write("HANOK WAGGA\n".getBytes(StandardCharsets.US_ASCII));out.write(new byte[]{0x1d,0x21,0x33});out.write("T01\n".getBytes(StandardCharsets.US_ASCII));out.write(new byte[]{0x1d,0x21,0x11,0x1d,0x42,0x01});out.write(" BBQ MEAT \n".getBytes(StandardCharsets.US_ASCII));out.write(new byte[]{0x1d,0x42,0x00,0x1d,0x21,0x00,0x1b,0x61,0x00});out.write("\nWagyu Scotch Fillet        x 2\nMarinated LA Short Rib     x 1\nPork Belly                  x 2\nChicken Thigh               x 1\n\n".getBytes(StandardCharsets.US_ASCII));out.write(new byte[]{0x1b,0x61,0x01,0x1b,0x45,0x01,0x1d,0x21,0x11});out.write("ITEMS: 6\n".getBytes(StandardCharsets.US_ASCII));out.write(new byte[]{0x1d,0x21,0x00,0x1b,0x45,0x00});out.write("ANDROID BRIDGE TEST\n\n\n".getBytes(StandardCharsets.US_ASCII));out.write(new byte[]{0x1d,0x56,0x00});out.flush();s.close();runOnUiThread(()->{status.setText("● Printer connected · test printed");status.setTextColor(Color.rgb(30,120,70));});}catch(Exception e){runOnUiThread(()->{status.setText("● Printer test failed: "+e.getMessage());status.setTextColor(Color.rgb(150,45,35));});}}).start();}
}
